version: '3.9'
services:
  todo-api:
    build: .
    command: rails db:migrate --trace && rails s
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - .:/app

  todo-front:
    build: ./frontend
    command: npm start
    ports:
      - "3001:3000"
    expose:
      - "3001"
    volumes:
      - ./frontend:/app

  nginx:
    build: ./middleware/nginx
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./middleware/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - todo-api
      - todo-front

  todo-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./db/conf/my.cnf:/etc/mysql/my.cnf"
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      BIND-ADDRESS: 0.0.0.0

volumes:
  mysql-data:
    driver: local