version: '3.9'
services:
  todo-api:
    build: .
    command: bundle exec rails s -p 3000
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - .:/app

  todo-front:
    build: ./frontend
    command: npm start
    ports:
      - "3001:3000"
    expose:
      - "3001"
    volumes:
      - ./frontend:/app

  nginx:
    build: ./middleware/nginx
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./middleware/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - todo-api
      - todo-front
